import './global.css';

export const metadata = {
  title: 'Welcome to Vision',
  description: 'Generated by create-nx-workspace',
  openGraph: {
    title: 'Welcome to Vision',
    description: 'Sexy Open Graph description',
    url: 'https://visionar.ai',
    siteName: 'Vision',
    images: [
      {
        url: 'https://visionar.ai/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Vision Open Graph Image',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
};
type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Readonly<Props>) {
  return children;
}
