import './global.css';

export const metadata = {
	description: 'Generated by create-nx-workspace',
	openGraph: {
		description: 'Sexy Open Graph description',
		images: [
			{
				alt: 'Vision Open Graph Image',
				height: 630,
				url: 'https://visionar.ai/og-image.png',
				width: 1200,
			},
		],
		locale: 'en_US',
		siteName: 'Vision',
		title: 'Welcome to Vision',
		type: 'website',
		url: 'https://visionar.ai',
	},
	title: 'Welcome to Vision',
};
type Props = {
	children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<Props>) {
	return children;
}
